# Organização no SonarCloud
sonar.organization=marielev

# A chave do projeto (Project Key)
sonar.projectKey=MarieleV_PlataformaCobranca

# Diz para o SonarCloud analisar apenas a pasta do nosso código fonte
sonar.sources=back-end/app

# (Opcional) Diz para ignorar arquivos de configuração e testes na hora de buscar bugs
sonar.exclusions=back-end/app/tests/**, back-end/app/seed.py